name: 'latest-release-action'
description: 'Outputs the number of unreleased commits'
author: 'cory taylor'
inputs:
  include-prerelease:
    description: Do you want to include pre-releases?
    default: false
outputs:
  unreleased-commit-count:
    description: How many commits are unreleased on master
  unreleased-commit-messages:
    description: Unreleased commit messages
  unreleased-diff-url:
    description: Diff Url
runs:
  using: 'node12'
  main: 'dist/index.js'